
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    permissions:
      contents: read

    env:
      NEXT_TELEMETRY_DISABLED: 1
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Typecheck + Lint (non-blocking for import-order)
        run: |
          npm run -s typecheck || true
          npm run -s lint || true

      - name: Export audit (blocking)
        run: node scripts/audit-exports.js

      - name: Build (prod)
        run: npm run build

      - name: Install Playwright browsers
        if: matrix.node-version == '22.x'
        run: npx playwright install --with-deps

      - name: Start server, run E2E + Lighthouse budgets (mobile)
        if: matrix.node-version == '22.x'
        run: |
          npx --yes start-server-and-test \
            "npm run start" \
            http-get://localhost:9000 \
            "bash -lc 'npx playwright test && npx lighthouse http://localhost:9000 --preset=perf --form-factor=mobile --screenEmulation.mobile --budget-path=./lighthouse-budgets.json --quiet --output=json --output-path=./lh.json'"

      - name: Upload Lighthouse report
        if: matrix.node-version == '22.x'
        uses: actions/upload-artifact@v4
        with:
          name: lh-json
          path: lh.json
